### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by Rishit-dagli** [Rishit-dagli/Transformer-in-Transformer#11]
The tests should check for the rank and shape of the output tensors, the test should override [`tf.test.TestCase`](https://www.tensorflow.org/api_docs/python/tf/test/TestCase) base class.

- [x] #15
- [x] #16
- [x] #18
- [x] #17

Feel free to take inspiration from:

- https://github.com/Rishit-dagli/Fast-Transformer/blob/main/fast_transformer/test_fast_transformer.py
- For parametrization feel free to follow https://stackoverflow.com/a/34094/11878567, can be used in the exact same way with [`subTest`](https://www.tensorflow.org/api_docs/python/tf/test/TestCase#subTest) in TensorFlow

**Comment by kaushik-42** [comment]
Hey, I'll give it a try! Thanks

**Comment by Rishit-dagli** [comment]
I have assigned this issue to you, feel free to go over 2 of the reference links if you are new to unit testing or [`tf.test`](https://www.tensorflow.org/api_docs/python/tf/test) in particular. Apart from the PR reviews feel free to ask if you have any more questions. Also, I'll leave it up to you if you want to address each of the checkboxes in their own PRs or combine them in a single PR.

**Comment by Rishit-dagli** [comment]
Hey, @kaushik-42 I will take this up for now after the DM you sent me.
